### ISSUE TITLE
Monix integration?

### ISSUE THREAD

**Issue by ngbinh** [OlivierBlanvillain/monadic-html#30] opened 2016-12-14 01:45 UTC
I am wondering if it is possible to use @alexandru https://github.com/monix/monix library for the reactive part of monadic-html? At the moment, our frontend is made reactive through Monix and it works very well.

**Comment by OlivierBlanvillain** [comment] 2016-12-14 09:21
`Rx` are synchronous, never complete and never fail, so they are fundamentally different from `Observable`.

But they should be no problem converting between the two: (I didn't compile the snippet, but that's the idea)

```scala
// This is reasonable, the resulting `Observable` will never fail nor complete.
def to[T](rx: Rx[T]): Observable[T] = {
  Observable.unsafeCreate[A] { out =>
    rx.foreach(out.onNext)
    Cancelable.empty
  }
}

// Should work, but the resulting `Rx` won't be aware or potential errors on obs...
def from[T](obs: Observable[T]): Rx[T] = {
  val rx = Rx.empty[T]
  obs.foreach(rx.:=)
  rx
}
```

**Comment by alexandru** [comment] 2016-12-14 09:49
@OlivierBlanvillain in the first sample it would be cool if that cancelable would work. Isn't there any way to unregister a handler?

In the second sample it would be cool if errors end up being logged (with `console.log` or something), which in this case won't happen because that `foreach` returns a `CancelableFuture[Unit]` which will swallow it. I would do something like:

```scala
def from[T](obs: Observable[T])(implicit s: Scheduler): Rx[T] = {
  val rx = Rx.empty[T]
  obs.subscribe(new Observer.Sync {
    def onNext(e: T) = {
      rx := e
      Continue
    }

    def onComplete() = ()
    def onError(ex: Throwable) = 
      s.reportError(ex)
  })
  rx
}
```

Also `Rx` is pretty cool, however the naming comes from `Rx.NET`, with the `x` being an obsession of Microsoft, coming from "*extensions*". So `Rx` comes from "*reactive extensions*" and refers primarily to the `Rx.NET` Observable pattern. They also have `Ix`, which comes from "*interactive extensions*", among others. In Monix I specifically avoided the name `Rx` because my `Observable` is a little different than theirs. And in software development, it's good to be precise.

Not trying to be pedantic or anything, but this will confuse people, because `Rx` is all about asynchronicity and refers specifically to the Observable pattern by Microsoft. This is just a small suggestion, but I would think of another name.

**Comment by OlivierBlanvillain** [comment] 2016-12-14 10:19
> Isn't there any way to unregister a handler?

There is, I was just being lazy in my answer. I actually copied your `Cancelable` pattern (which leads to very clean code), one simply needs to convert `mhtml.Cancelable` returned by [foreach](https://github.com/OlivierBlanvillain/monadic-html/blob/master/monadic-rx/shared/src/main/scala/mhtml/rx.scala#L10) to a `monix.execution.Cancelable`, and give that to the `unsafeCreate`.

> In the second sample it would be cool if errors end up being logged

That's indeed a minimum, but it ultimately depends on how the application should behave on errors. For example, to implement something like gmail where everything *keeps on working* when the websocket connection is lost, one probably needs a lot of machinery between the can fail can terminate world, and the pure UI rendering one :smile:. A real time game would be different: UI would likely be completely pause until the connection is restored.

> This is just a small suggestion, but I would think of another name.

Didn't know the sorry behind the name, thanks for pointing it out! I'm opening #31 to discuss this if you have suggestions.

**Comment by ngbinh** [comment] 2016-12-14 10:54
@OlivierBlanvillain is there a specific reason for `Rx` to be synchronous? As far as I know,  non-blocking, asynchronous constructs work better on browser.

**Comment by OlivierBlanvillain** [comment] 2016-12-14 12:03
In the case of UI rendering this should be an implementation detail: you should not be able to observe a difference between synchronicity/asynchronicity.

**Comment by ngbinh** [comment] 2016-12-15 03:32
> Rx are synchronous, never complete and never fail, so they are fundamentally different from Observable.

So does that mean we should be able to replace `Rx` with `monix` `Observable`? I am quite keen on using `monix` directly if `Rx` does not offer any advantages.

**Comment by OlivierBlanvillain** [comment] 2016-12-15 13:03
From for functionality stand point, yes: monix `Observable` APIs are a super set of `mhtml.Rx`. However I think `Observable`s are not really an appropriate abstraction for building UI interactions in a monadic style because of how easy it is to create memory leaks. Consider the following example:

```scala
val source0: Observable[Int] = ...
val source1: Observable[Int] = ...

val target = for {
  v0 <- source0
  v1 <- source1
} yield v0 + v1
```

Every time `source0` changes this created a new `Observable` which will never be garbage collected (assuming source0 & 1 never terminate)... `mhtml.Rx` was designed specifically to address this issue and should make it hard to accidentally leak memory (every if we do not yet have a proper way to test this...).

**Comment by OlivierBlanvillain** [comment] 2017-08-25 12:08
I'm going to close this from now. We have a very simpler integration with `scala.concurrent.Future` [it's in this file](https://github.com/OlivierBlanvillain/monadic-html/blob/d18022f5ec09f0e6603bbf6e3982f2a1b0293f12/monadic-rx/shared/src/main/scala/mhtml/future.scala), ff someone is interested having a similar type of integration with Monix I'm would be happy to publish that as a separate artifact!

**Closed by OlivierBlanvillain** 2017-08-25 12:08 UTC

**Comment by alexandru** [comment] 2017-08-25 19:06
@OlivierBlanvillain I just noticed your sample above.

So combining 2 observables like that is not going to work out for obvious reasons, given that `Observable` is a lawful monadic type.

What you wanted there is `combineLatest`:

```scala
Observable.combineLatestMap2(source0, source1) { (v0, v1) => v0 + v1 }
```

Just an FYI.

**Comment by OlivierBlanvillain** [comment] 2017-08-26 08:51
> So combining 2 observables like that is not going to work out for obvious reasons, given that Observable is a lawful monadic type.

@alexandru I don't think monad laws and memory leaks in this example are directly related. My understanding is that these leaks are a consequence design decisions on `Observable` that make more suitable to model stream of data going through the network than to build local single threaded user interfaces.

`mhtml.Rx` avoids memory leaks by being push-based and having  `flatMap` "unregister" the previous subscription every time a new event fires on the `Rx` being flatmapped on (`source0`). This way, the intermediate structure that is no longer in use (and would leak otherwise) becomes garbage collectable. If you are interested we have [some tests](https://github.com/OlivierBlanvillain/monadic-html/blob/master/monadic-rx/shared/src/test/scala/mhtml/RxTests.scala#L45) showing the absence of leaks and [a proof](https://github.com/OlivierBlanvillain/monadic-html/blob/master/monadic-rx-cats/src/main/scala/mhtml/cats.scala#L9-L205) for the monad laws :)

**Comment by alexandru** [comment] 2017-08-27 13:53
OK, you're describing `switchMap` from Rx. Monix has that too.

Also the `flatMap` in Monix does not leak memory because the source gets back-pressured. In case the source cannot be paused, then by design buffering is forced at the source (I.e. You can't build a source that can't be paused without an explicit buffer) and that chosen buffer can start dropping events.

Not having leaks and unbounded buffering is my initial motivation for building Monix.

And btw, if you have asynchronous boundaries *anywhere*, without a back pressuring protocol in that communion, you basically have unbounded buffering, even if it's implicit (e.g. pushing runnables in a thread pool). The original Rx.NET is problematic because of this, whereas Monix is not.
